config/routes.rb
FirstApp::Application.routes.draw do
  	
  resources	:drinks
  
   	

end

app/models/drink.rb
class Drink < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController

	def index
		#will have template
		@drinks = Drink.all
	end
	
	def show
		#will have template
		@drink = Drink.find(params[:id])
	end
	
	def new # display the form for new record
		#will have template
		@drink = Drink.new		
	end
	
	def create #save new record
		#save and redirect
		@drink = Drink.new(allowed_params)
		
		if @drink.save
			redirect_to drinks_path
		else
			redender 'new'
		end
	end
	
	def edit # display for existing record
		# will have template
		@drink = Drink.find(params[:id])
	end
	
	def update # save changes
		
		@drink = Drink.find(params[:id])
		if @drink.update_attributes(allowed_params)
			redirect_to drinks_path
		else	
			redender 'new'
		end		
	end
	
	def destroy
		# will destroy and redirect
		@drink = Drink.find(params[:id])
		@drink.destroy
		redirect_to drinks_path
	end
	
	private 
		def allowed_params
			params.require(:drink).permit(:name, :size)
		end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/views/drinks/edit.html.erb
<%= form_for @drink do |f| %>

	<%= f.label :name %> <br />
	<%= f.text_field :name %>
	
	<%= f.label :size %> <br />
	<%= f.text_field :size %>
	
	<%= f.submit 'Update Drink' %>
<% end %>

app/views/drinks/index.html.erb
<%= link_to 'Add Drink', new_drink_path %>

<% @drinks.each do |drink| %>
	<p>
		Name: <%= link_to drink.name, drink_path(drink) %><br />
		Size: <%= drink.size %> | <%= link_to 'Edit', 
			edit_drink_path(drink) %> | <%= link_to '
			Delete', drink, method: :delete %>
	</p>
<% end %>

app/views/drinks/new.html.erb
<%= form_for @drink do |f| %>

	<%= f.label :name %> 
	<%= f.text_field :name %> <br />
	
	<%= f.label :size %> 
	<%= f.text_field :size %> <br />
	
	<%= f.submit 'Create Drink' %>
<% end %>

app/views/drinks/show.html.erb
<h1><%= @drink.name %></h1>

<%= link_to 'go back', drinks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>